### ISSUE TITLE
Make the Installation Process of Cloudflow Components Testable

### ISSUE THREAD

**Issue by eschizoid** [lightbend/cloudflow#108]
**Is your feature request related to a problem? Please describe.**
As today the installation and deployment of all K8s custom resources required by Cloudflow have no tests. The reason probably is because this was unfortunately done with `bash` from the beginning. 

**Is your feature request related to a specific runtime of Cloudflow or applicable for all runtimes?**
All runtimes

**Describe the solution you'd like**
I would like to use a programming language that can be tested so we can warranty that the installation is never broken (this happened two times during the last week).

**Describe alternatives you've considered**
Perhaps the most natural solution would be `terraform` since we can easily build reusable modules that could potentially be used for deploying to the 3 major cloud providers: AWS, Azure, and GCP.

Another potential good fit could be https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html. Since we have a lot of custom steps during the installation process (`helm init`, etc.), having a programming language can give us this flexibility. CDK supports the following languages: 
- TypeScript
- Python
- Java
- C#

**Additional context**
I am willing to help with this task if we pick `terraform`, or `scala/java/python` if we move with the `CDK` route. FWIW, I rather do `scala` or `terraform`, but I would be also comfortable doing it in python (unfortunately no golang support yet, https://github.com/aws/aws-cdk/issues/547).

**Comment by agemooij** [comment]
Thanks for the suggestion @eschizoid . We are currently looking into what it would take to build end-to-end integration testing support for Cloudflow, and Terraform is on the discussion list for automating cluster creation and other tasks.

We have a meeting planned for next week (Jan. 27th-30th 2020) to discus this and other installer-related topics. Some decisions made there could have an impact on this issue so I hope I can tell you more after that.

**Comment by agemooij** [comment]
Hi @eschizoid . It took a little longer to get back to you on this. apologies for the delay.

During our team meeting we have made some decisions for the future that will impact the suggestions you made in this issue. In brief, we decided to:

1. open source our "enterprise installer" (see below)
1. start work on automated end-to-end testing capabilities

Currently, we support two installers. The OSS installer is a simplified version of our original installer but in the mean time we have developed a new installer that is based on the operator pattern, e.g. a Cloudflow installation can be expressed as a Kubernetes Custom Resource (CR) and then the installation operator will take care of everything from inside the cluster. We then wrap that in a very simple CLI for asking a few questions to create the CR so you can just type `cloudflow install`.

That new installer was original thought to be an enterprise feature but it is clear that that doesn't make a lot of sense since everybody needs a great installation experience. so we will be working on open sourcing that in the Q1 2020 timeframe.

Next to that there will still be a need to verify that an installation has succeeded. Some of that will be built into the installation operator itself, e.g. an installation either succeeds or it doesn't and the operator knows this state and makes it available as a `status` field on the installation CR.

We are also planning to start work on automated end-to-end testing for Cloudflow, from cluster creation to installation and app deployment, to ensure that no changes to master break any parts of the chain. That will definitely take us some more time but we plan to start by publishing the design proposal so you guys can help us get there faster.

I hope this explains where we are going with the installer and its testability. Please do let us know if you have any questions about this stuff!

**Comment by eschizoid** [comment]
@agemooij Thanks for sharing this information, happy to hear all this great news!

I can't wait to see the design proposal and start helping :)
