### ISSUE TITLE
When using the new operator-based installer, it says "Error: Could not find tiller"

### ISSUE THREAD

**Issue by maasg** [lightbend/cloudflow#436]
I'm trying to use the operator-based installer on the current `master`
Following the instructions in the `readme`, I downloaded https://github.com/lightbend/cloudflow/releases/download/v1.3.3/bootstrap-install-script-1.3.3.sh

When executing it, I get:
```
 $ ./bootstrap-install-script-1.3.3.sh 
Error: could not find tiller
```

**Comment by yuchaoran2011** [comment]
This error is caused by https://github.com/lightbend/cloudflow/blob/master/installer/release/bootstrap-install-script.sh.template#L21. I didn't run into it because my machine has Helm 3 installed, while @maasg has Helm 2. One of three things we can do:
* Remove this line from the bootstrap script. Tell the user to install NFS if they need it. Let them handle Tiller if they are still using Helm 2.
* Leave the script in its current status and update the doc to say we only support Helm 3.
* Update the bootstrap script to detect the Helm version that the user has. If it's Helm 2 and Tiller isn't running, report an error.
Which option do you guys prefer? @maasg @RayRoestenburg

**Comment by maasg** [comment]
Can we expect all users to have migrated to Helm 3 already? 
We could only support helm 3 but document a procedure for Helm 2 users.
Then, detect the helm version and point the user to the procedure, in case they are using Helm 2.
Do we need helm only for `nfs`? I think we have done a few iterations around the `nfs` support. 
We could move it out of the installer and add it as a pre-requisite?  
That was the case with the enterprise installer, as we didn't expect `nfs` to be required, but for a quick start, it was crappy to do. Especially if you don't know how to install tiller (like me ;-) ). -- back then, I was installing from the script and then installing the `install operator` to get this working.

**Comment by yuchaoran2011** [comment]
After discussing with Ray, I'll run the Helm command in a container with Helm 3. This way we don't have to restrict the user to a specific Helm version and we don't need to worry about Tiller :)
